sudo: required

services:
- docker

before_install:
- docker pull jeffbush001/nyuzi-build	

script:
- docker run -v $TRAVIS_BUILD_DIR:/root/NyuziProcessor -w /root/NyuziProcessor jeffbush001/nyuzi-build "(cd tests/cosimulation && ./generate_random.py -m 3) && make test"


